# Generated by Django 3.1.3 on 2021-01-03 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_contacts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='massage',
            field=models.TextField(max_length=700),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='subject',
            field=models.TextField(max_length=200),
        ),
    ]
