# Generated by Django 3.1.3 on 2021-01-04 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_auto_20210104_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='massage',
            field=models.CharField(max_length=700),
        ),
        migrations.AlterField(
            model_name='contact',
            name='subject',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='massage',
            field=models.TextField(max_length=700),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='subject',
            field=models.TextField(max_length=200),
        ),
    ]
