# Generated by Django 3.1.3 on 2021-01-02 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_contacts'),
    ]

    operations = [
        migrations.DeleteModel(
            name='contacts',
        ),
    ]
